title = "writing code with paul"
baseURL = "https://pmsanford.github.io"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "check out the posts if you want"
  facebook = "https://www.facebook.com/psanf"
  twitter = ""
  instagram = "https://www.instagram.com/paulmsanford/"
  youtube = ""
  github = "https://github.com/pmsanford"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/paul-sanford-74767613/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "hero-chop.jpg"
  recent_posts_number = 2
